# LSTM MODEL - Blocked CV
import torch.nn as nn 
import torch

class LSTM_model(nn.Module):
    def __init__(self, input_dim, hidden_dim1, num_layers, Animal):
        super(LSTM_model, self).__init__()
        self.hidden_dim1 = hidden_dim1
        self.num_layers = num_layers
        self.Animal = Animal
        self.lstm = nn.LSTM(input_dim, hidden_dim1, num_layers, batch_first=True, bias=True, dropout=0.3)
        self.relu = nn.ReLU()

        ## LSTM --> Session-Specific Linear Decoder --> Neural PCs
        # Linear Decoder --> nn.Linear(128 latent dimensions, # of Neural PCs)

        if Animal == 0:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                 
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })

        elif Animal == 1:
            self.fc_layers = nn.ModuleDict({                 
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })
        elif Animal == 2:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                  
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })
        elif Animal == 3:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                   
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })
        elif Animal == 4:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                   
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })
        elif Animal == 5:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                   
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '38': nn.Linear(hidden_dim1, 43),
                '39': nn.Linear(hidden_dim1, 54),
                '40': nn.Linear(hidden_dim1, 49),
                '41': nn.Linear(hidden_dim1, 47),
                '42': nn.Linear(hidden_dim1, 103),
                '43': nn.Linear(hidden_dim1, 67),
            })
        elif Animal == 6:
            self.fc_layers = nn.ModuleDict({
                '1': nn.Linear(hidden_dim1, 80),
                '2': nn.Linear(hidden_dim1, 55),
                '3': nn.Linear(hidden_dim1, 96),
                '4': nn.Linear(hidden_dim1, 71),
                '5': nn.Linear(hidden_dim1, 62), 
                '6': nn.Linear(hidden_dim1, 47),                   
                '7': nn.Linear(hidden_dim1, 72),
                '8': nn.Linear(hidden_dim1, 60),
                '9': nn.Linear(hidden_dim1, 101),
                '10': nn.Linear(hidden_dim1, 65),
                '11': nn.Linear(hidden_dim1, 45),
                '12': nn.Linear(hidden_dim1, 51),
                '13': nn.Linear(hidden_dim1, 54),
                '14': nn.Linear(hidden_dim1, 51), 
                '15': nn.Linear(hidden_dim1, 61), 
                '16': nn.Linear(hidden_dim1, 52),
                '17': nn.Linear(hidden_dim1, 77),
                '18': nn.Linear(hidden_dim1, 61),
                '19': nn.Linear(hidden_dim1, 86),
                '20': nn.Linear(hidden_dim1, 65),
                '21': nn.Linear(hidden_dim1, 36),
                '22': nn.Linear(hidden_dim1, 52),
                '23': nn.Linear(hidden_dim1, 59),
                '24': nn.Linear(hidden_dim1, 37),
                '25': nn.Linear(hidden_dim1, 48),
                '26': nn.Linear(hidden_dim1, 59),
                '27': nn.Linear(hidden_dim1, 44),
                '28': nn.Linear(hidden_dim1, 59),
                '29': nn.Linear(hidden_dim1, 71),
                '30': nn.Linear(hidden_dim1, 89),
                '31': nn.Linear(hidden_dim1, 92),
                '32': nn.Linear(hidden_dim1, 95),
                '33': nn.Linear(hidden_dim1, 65),
                '34': nn.Linear(hidden_dim1, 100),
                '35': nn.Linear(hidden_dim1, 76),
                '36': nn.Linear(hidden_dim1, 63),
                '37': nn.Linear(hidden_dim1, 82),
            })
    def forward(self, x):
        # LSTM forward pass
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim1).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim1).to(x.device)
        out, _ = self.lstm(x, (h0, c0))
        out = self.relu(out)

        return out
